#! /usr/bin/python

import sys
import json
from pygments import highlight, lexers, formatters

raw_data = sys.stdin.readlines()[0]
json_object = json.loads(raw_data)

if len(sys.argv) > 1:
    access = sys.argv[1]
    value_string =  'json_object' + access
    json_object = eval(value_string)

formatted_json = json.dumps(json_object, sort_keys=True, indent=4)
colorful_json = highlight(unicode(formatted_json, 'UTF-8'), lexers.JsonLexer(), formatters.TerminalFormatter())
print(colorful_json)
